export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_USER_BYID_REQUEST = "GET_USER_BYID_REQUEST";
export const GET_USER_BYID_SUCCESS = "GET_USER_BYID_SUCCESS";
export const GET_USER_BYID_FAILURE = "GET_USER_BYID_FAILURE";

export const UPDATE_USER_BYID_REQUEST = "UPDATE_USER_BYID_REQUEST";
export const UPDATE_USER_BYID_SUCCESS = "UPDATE_USER_BYID_SUCCESS";
export const UPDATE_USER_BYID_FAILURE = "UPDATE_USER_BYID_FAILURE";

export const DELETE_USER_BYID_REQUEST = "DELETE_USER_BYID_REQUEST";
export const DELETE_USER_BYID_SUCCESS = "DELETE_USER_BYID_SUCCESS";
export const DELETE_USER_BYID_FAILURE = "DELETE_USER_BYID_FAILURE";
